# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://{{host}}:80/api/v0.1/characters/save
Content-Type: application/json

< testCharactersForPlayer1.json

###

POST http://{{host}}:80/api/v0.1/characters/save
Content-Type: application/json

< testCharactersForPlayer2.json

###

POST http://{{host}}:80/api/v0.1/characters/save
Content-Type: application/json

< allCharacters.json

###

POST http://{{host}}:80/api/v0.1/player/save
Content-Type: application/json

< testPlayer1.json

###

POST http://{{host}}:80/api/v0.1/player/save
Content-Type: application/json

< testPlayer2.json

###

GET http://{{host}}:80/api/v0.1/characters/fetch

###

GET http://{{host}}:80/api/v0.1/character/fetch/4607255831

###

GET http://{{host}}:80/api/v0.1/player/fetch/4607255831

###

GET http://{{host}}:80/api/v0.1/players/fetch

###
